// Static configuration extracted from the preserved userscript behavior.
// Keep values stable unless a deliberate theme/audio behavior change is documented.

export const SOUND_PRESETS = {
    arcade: {
        correct: [
            {
                freq: 440,
                streakScale: 20,
                maxFreq: 1200,
                duration: 0.09,
                volume: 0.12,
                volumeStreakScale: 0.003,
                maxVolume: 0.22,
                type: 'square',
                endFreqScale: 1.04,
            },
            {
                freq: 660,
                streakScale: 30,
                maxFreq: 1800,
                duration: 0.12,
                volume: 0.15,
                type: 'square',
                delay: 0.04,
                endFreqScale: 1.1,
                every: 5,
                skipLite: true,
            },
            {
                freq: 880,
                streakScale: 40,
                maxFreq: 2400,
                duration: 0.15,
                volume: 0.12,
                type: 'triangle',
                delay: 0.08,
                every: 10,
                skipLite: true,
            },
            {
                freq: 1100,
                streakScale: 50,
                maxFreq: 2600,
                duration: 0.2,
                volume: 0.28,
                type: 'sine',
                delay: 0.03,
                chance: 0.07,
                skipLite: true,
            },
        ],
        incorrect: [
            { freq: 300, duration: 0.15, volume: 0.25, type: 'sawtooth', endFreqScale: 0.7 },
            {
                freq: 180,
                duration: 0.2,
                volume: 0.2,
                type: 'sawtooth',
                delay: 0.12,
                skipLite: true,
            },
        ],
        wordComplete: [
            {
                freq: 523,
                wordScale: 6,
                maxFreq: 643,
                duration: 0.18,
                volume: 0.22,
                type: 'triangle',
            },
            {
                freq: 659,
                wordScale: 6,
                maxFreq: 779,
                duration: 0.18,
                volume: 0.22,
                type: 'triangle',
                delay: 0.12,
                skipLite: true,
            },
            {
                freq: 784,
                wordScale: 6,
                maxFreq: 904,
                duration: 0.18,
                volume: 0.22,
                type: 'triangle',
                delay: 0.24,
                skipLite: true,
            },
        ],
        multiplierUp: [
            {
                freqByMultiplier: [330, 440, 550, 660, 880],
                duration: 0.1,
                volume: 0.2,
                type: 'square',
            },
            {
                freqByMultiplier: [495, 660, 825, 990, 1320],
                duration: 0.14,
                volume: 0.18,
                type: 'square',
                delay: 0.06,
                skipLite: true,
            },
            {
                freqByMultiplier: [660, 880, 1100, 1320, 1760],
                duration: 0.18,
                volume: 0.14,
                type: 'triangle',
                delay: 0.12,
                skipLite: true,
            },
        ],
        comboBreak: [
            { freq: 400, duration: 0.18, volume: 0.22, type: 'sawtooth', skipLite: true },
            { freq: 300, duration: 0.18, volume: 0.22, type: 'sawtooth', delay: 0.08 },
            {
                freq: 200,
                duration: 0.18,
                volume: 0.22,
                type: 'sawtooth',
                delay: 0.16,
                skipLite: true,
            },
        ],
        timeout: [
            { freq: 260, duration: 0.16, volume: 0.18, type: 'sawtooth' },
            {
                freq: 180,
                duration: 0.18,
                volume: 0.16,
                type: 'triangle',
                delay: 0.1,
                skipLite: true,
            },
        ],
        sessionComplete: [
            { freq: 523, duration: 0.22, volume: 0.2, type: 'triangle' },
            { freq: 659, duration: 0.22, volume: 0.2, type: 'triangle', delay: 0.14 },
            { freq: 784, duration: 0.22, volume: 0.2, type: 'triangle', delay: 0.28 },
            { freq: 1047, duration: 0.4, volume: 0.25, type: 'sine', delay: 0.65, skipLite: true },
        ],
    },
    starfield: {
        correct: [
            {
                freq: 740,
                streakScale: 8,
                maxFreq: 1120,
                duration: 0.1,
                volume: 0.13,
                type: 'sine',
                detune: -5,
            },
            {
                freq: 1110,
                streakScale: 12,
                maxFreq: 1660,
                duration: 0.16,
                volume: 0.08,
                type: 'triangle',
                delay: 0.08,
                detune: 7,
                skipLite: true,
            },
            {
                freq: 1480,
                streakScale: 10,
                maxFreq: 2200,
                duration: 0.22,
                volume: 0.045,
                type: 'sine',
                delay: 0.16,
                chance: 0.28,
                skipLite: true,
            },
        ],
        incorrect: [
            { freq: 220, duration: 0.18, volume: 0.13, type: 'triangle' },
            {
                freq: 165,
                duration: 0.2,
                volume: 0.1,
                type: 'sine',
                delay: 0.12,
                endFreqScale: 0.82,
                skipLite: true,
            },
        ],
        wordComplete: [
            { freq: 587, wordScale: 4, duration: 0.18, volume: 0.13, type: 'sine', detune: -4 },
            {
                freq: 880,
                wordScale: 4,
                duration: 0.22,
                volume: 0.1,
                type: 'triangle',
                delay: 0.16,
                detune: 5,
                skipLite: true,
            },
            {
                freq: 1175,
                wordScale: 4,
                duration: 0.28,
                volume: 0.055,
                type: 'sine',
                delay: 0.34,
                skipLite: true,
            },
        ],
        multiplierUp: [
            {
                freqByMultiplier: [440, 554, 659, 880, 1175],
                duration: 0.14,
                volume: 0.13,
                type: 'sine',
            },
            {
                freqByMultiplier: [880, 1108, 1318, 1760, 2350],
                duration: 0.18,
                volume: 0.08,
                type: 'triangle',
                delay: 0.1,
                skipLite: true,
            },
        ],
        comboBreak: [{ freq: 185, duration: 0.24, volume: 0.12, type: 'triangle' }],
        timeout: [{ freq: 196, duration: 0.22, volume: 0.12, type: 'sine' }],
        sessionComplete: [
            { freq: 659, duration: 0.2, volume: 0.12, type: 'sine' },
            { freq: 988, duration: 0.28, volume: 0.1, type: 'triangle', delay: 0.18 },
        ],
    },
    nebula: {
        correct: [
            {
                freq: 659,
                streakScale: 10,
                maxFreq: 1280,
                duration: 0.12,
                volume: 0.13,
                type: 'sine',
                detune: -6,
            },
            {
                freq: 987,
                streakScale: 14,
                maxFreq: 1920,
                duration: 0.18,
                volume: 0.09,
                type: 'sine',
                delay: 0.09,
                detune: 8,
                skipLite: true,
            },
            {
                freq: 1318,
                streakScale: 16,
                maxFreq: 2400,
                duration: 0.2,
                volume: 0.052,
                type: 'triangle',
                delay: 0.2,
                chance: 0.34,
                skipLite: true,
            },
        ],
        incorrect: [
            { freq: 277, duration: 0.16, volume: 0.15, type: 'triangle', endFreqScale: 0.88 },
            {
                freq: 208,
                duration: 0.22,
                volume: 0.1,
                type: 'sine',
                delay: 0.1,
                detune: -8,
                skipLite: true,
            },
        ],
        wordComplete: [
            { freq: 523, wordScale: 5, duration: 0.18, volume: 0.13, type: 'sine' },
            { freq: 784, wordScale: 5, duration: 0.2, volume: 0.11, type: 'sine', delay: 0.14 },
            {
                freq: 1175,
                wordScale: 5,
                duration: 0.22,
                volume: 0.08,
                type: 'triangle',
                delay: 0.28,
                skipLite: true,
            },
        ],
        multiplierUp: [
            {
                freqByMultiplier: [392, 523, 659, 784, 1047],
                duration: 0.16,
                volume: 0.13,
                type: 'sine',
            },
            {
                freqByMultiplier: [784, 1047, 1318, 1568, 2093],
                duration: 0.2,
                volume: 0.08,
                type: 'triangle',
                delay: 0.12,
                skipLite: true,
            },
        ],
        comboBreak: [{ freq: 247, duration: 0.24, volume: 0.12, type: 'triangle' }],
        timeout: [{ freq: 220, duration: 0.22, volume: 0.11, type: 'sine' }],
        sessionComplete: [
            { freq: 523, duration: 0.2, volume: 0.12, type: 'sine' },
            { freq: 784, duration: 0.24, volume: 0.11, type: 'sine', delay: 0.18 },
            { freq: 1175, duration: 0.3, volume: 0.09, type: 'triangle', delay: 0.38 },
        ],
    },
    grid: {
        correct: [
            {
                freq: 660,
                streakScale: 18,
                maxFreq: 1500,
                duration: 0.07,
                volume: 0.16,
                type: 'square',
                endFreqScale: 1.35,
            },
            {
                freq: 990,
                streakScale: 24,
                maxFreq: 2100,
                duration: 0.08,
                volume: 0.12,
                type: 'triangle',
                delay: 0.04,
                endFreqScale: 1.18,
                skipLite: true,
            },
        ],
        incorrect: [
            { freq: 220, duration: 0.12, volume: 0.2, type: 'sawtooth', endFreqScale: 0.48 },
            {
                freq: 132,
                duration: 0.18,
                volume: 0.16,
                type: 'square',
                delay: 0.08,
                skipLite: true,
            },
        ],
        wordComplete: [
            { freq: 440, wordScale: 8, duration: 0.1, volume: 0.16, type: 'square' },
            {
                freq: 880,
                wordScale: 8,
                duration: 0.12,
                volume: 0.12,
                type: 'triangle',
                delay: 0.08,
                skipLite: true,
            },
        ],
        multiplierUp: [
            {
                freqByMultiplier: [392, 523, 659, 784, 1047],
                duration: 0.1,
                volume: 0.16,
                type: 'square',
            },
            {
                freqByMultiplier: [784, 1047, 1318, 1568, 2093],
                duration: 0.12,
                volume: 0.11,
                type: 'square',
                delay: 0.06,
                skipLite: true,
            },
        ],
        comboBreak: [
            { freq: 330, duration: 0.1, volume: 0.18, type: 'sawtooth' },
            {
                freq: 165,
                duration: 0.16,
                volume: 0.14,
                type: 'square',
                delay: 0.08,
                skipLite: true,
            },
        ],
        timeout: [{ freq: 185, duration: 0.18, volume: 0.15, type: 'square' }],
        sessionComplete: [
            { freq: 523, duration: 0.12, volume: 0.14, type: 'square' },
            { freq: 784, duration: 0.12, volume: 0.13, type: 'square', delay: 0.1 },
            { freq: 1047, duration: 0.18, volume: 0.11, type: 'triangle', delay: 0.22 },
        ],
    },
    gamecenter: {
        correct: [
            {
                freq: 784,
                streakScale: 18,
                maxFreq: 1600,
                duration: 0.08,
                volume: 0.17,
                type: 'square',
                endFreqScale: 1.18,
            },
            {
                freq: 1175,
                streakScale: 28,
                maxFreq: 2300,
                duration: 0.08,
                volume: 0.13,
                type: 'square',
                delay: 0.05,
                skipLite: true,
            },
            {
                freq: 1568,
                streakScale: 28,
                maxFreq: 2700,
                duration: 0.08,
                volume: 0.09,
                type: 'square',
                delay: 0.11,
                every: 3,
                skipLite: true,
            },
        ],
        incorrect: [
            { freq: 262, duration: 0.13, volume: 0.22, type: 'sawtooth' },
            {
                freq: 175,
                duration: 0.19,
                volume: 0.17,
                type: 'sawtooth',
                delay: 0.1,
                skipLite: true,
            },
        ],
        wordComplete: [
            { freq: 659, wordScale: 7, duration: 0.12, volume: 0.18, type: 'square' },
            { freq: 880, wordScale: 7, duration: 0.12, volume: 0.16, type: 'square', delay: 0.11 },
            {
                freq: 1318,
                wordScale: 7,
                duration: 0.16,
                volume: 0.12,
                type: 'triangle',
                delay: 0.22,
                skipLite: true,
            },
        ],
        multiplierUp: [
            {
                freqByMultiplier: [523, 659, 784, 988, 1318],
                duration: 0.09,
                volume: 0.18,
                type: 'square',
            },
            {
                freqByMultiplier: [1047, 1318, 1568, 1976, 2637],
                duration: 0.12,
                volume: 0.12,
                type: 'square',
                delay: 0.08,
                skipLite: true,
            },
        ],
        comboBreak: [
            { freq: 392, duration: 0.14, volume: 0.2, type: 'sawtooth' },
            { freq: 262, duration: 0.18, volume: 0.16, type: 'sawtooth', delay: 0.09 },
        ],
        timeout: [{ freq: 247, duration: 0.18, volume: 0.16, type: 'sawtooth' }],
        sessionComplete: [
            { freq: 659, duration: 0.12, volume: 0.17, type: 'square' },
            { freq: 784, duration: 0.12, volume: 0.16, type: 'square', delay: 0.12 },
            { freq: 1047, duration: 0.16, volume: 0.14, type: 'square', delay: 0.24 },
            {
                freq: 1568,
                duration: 0.22,
                volume: 0.12,
                type: 'triangle',
                delay: 0.42,
                skipLite: true,
            },
        ],
    },
    shrine: {
        correct: [
            {
                freq: 659,
                streakScale: 5,
                maxFreq: 880,
                duration: 0.16,
                volume: 0.12,
                type: 'sine',
                detune: -7,
            },
            {
                freq: 988,
                streakScale: 5,
                maxFreq: 1320,
                duration: 0.24,
                volume: 0.08,
                type: 'triangle',
                delay: 0.12,
                detune: 6,
                skipLite: true,
            },
        ],
        incorrect: [
            { freq: 196, duration: 0.16, volume: 0.12, type: 'triangle', endFreqScale: 0.92 },
            { freq: 147, duration: 0.18, volume: 0.09, type: 'sine', delay: 0.12, skipLite: true },
        ],
        wordComplete: [
            { freq: 523, wordScale: 3, duration: 0.18, volume: 0.12, type: 'sine' },
            {
                freq: 659,
                wordScale: 3,
                duration: 0.22,
                volume: 0.1,
                type: 'triangle',
                delay: 0.18,
                skipLite: true,
            },
            {
                freq: 1047,
                wordScale: 2,
                duration: 0.34,
                volume: 0.055,
                type: 'sine',
                delay: 0.38,
                skipLite: true,
            },
        ],
        multiplierUp: [
            {
                freqByMultiplier: [330, 392, 523, 659, 784],
                duration: 0.18,
                volume: 0.12,
                type: 'sine',
            },
            {
                freqByMultiplier: [660, 784, 1046, 1318, 1568],
                duration: 0.22,
                volume: 0.08,
                type: 'triangle',
                delay: 0.16,
                skipLite: true,
            },
        ],
        comboBreak: [{ freq: 174, duration: 0.22, volume: 0.09, type: 'triangle' }],
        timeout: [{ freq: 164, duration: 0.24, volume: 0.08, type: 'sine' }],
        sessionComplete: [
            { freq: 523, duration: 0.24, volume: 0.1, type: 'sine' },
            { freq: 659, duration: 0.28, volume: 0.09, type: 'triangle', delay: 0.22 },
        ],
    },
    nightview: {
        correct: [
            {
                freq: 587,
                streakScale: 3,
                maxFreq: 740,
                duration: 0.18,
                volume: 0.09,
                type: 'sine',
                detune: -8,
            },
            {
                freq: 784,
                streakScale: 4,
                maxFreq: 988,
                duration: 0.28,
                volume: 0.052,
                type: 'triangle',
                delay: 0.14,
                detune: 5,
                skipLite: true,
            },
        ],
        incorrect: [
            { freq: 185, duration: 0.18, volume: 0.085, type: 'triangle', endFreqScale: 0.9 },
            { freq: 139, duration: 0.26, volume: 0.052, type: 'sine', delay: 0.16, skipLite: true },
        ],
        wordComplete: [
            { freq: 440, wordScale: 2, duration: 0.24, volume: 0.085, type: 'sine' },
            {
                freq: 659,
                wordScale: 2,
                duration: 0.3,
                volume: 0.062,
                type: 'triangle',
                delay: 0.2,
                skipLite: true,
            },
            {
                freq: 880,
                wordScale: 2,
                duration: 0.42,
                volume: 0.038,
                type: 'sine',
                delay: 0.46,
                skipLite: true,
            },
        ],
        multiplierUp: [
            {
                freqByMultiplier: [330, 392, 440, 523, 659],
                duration: 0.2,
                volume: 0.08,
                type: 'sine',
            },
            {
                freqByMultiplier: [494, 587, 659, 784, 988],
                duration: 0.32,
                volume: 0.046,
                type: 'triangle',
                delay: 0.18,
                skipLite: true,
            },
        ],
        comboBreak: [{ freq: 164, duration: 0.24, volume: 0.06, type: 'triangle' }],
        timeout: [{ freq: 147, duration: 0.28, volume: 0.055, type: 'sine' }],
        sessionComplete: [
            { freq: 440, duration: 0.26, volume: 0.074, type: 'sine' },
            { freq: 587, duration: 0.34, volume: 0.06, type: 'triangle', delay: 0.24 },
            { freq: 880, duration: 0.56, volume: 0.04, type: 'sine', delay: 0.58 },
        ],
    },
    matrix: {
        correct: [
            {
                freq: 880,
                streakScale: 12,
                maxFreq: 1480,
                duration: 0.055,
                volume: 0.13,
                type: 'square',
                endFreqScale: 0.62,
            },
            {
                freq: 1320,
                streakScale: 18,
                maxFreq: 2200,
                duration: 0.06,
                volume: 0.09,
                type: 'square',
                delay: 0.045,
                endFreqScale: 1.42,
                skipLite: true,
            },
        ],
        incorrect: [
            { freq: 180, duration: 0.09, volume: 0.16, type: 'sawtooth', endFreqScale: 0.42 },
            {
                freq: 90,
                duration: 0.12,
                volume: 0.11,
                type: 'square',
                delay: 0.08,
                endFreqScale: 1.8,
                skipLite: true,
            },
        ],
        wordComplete: [
            { freq: 660, wordScale: 6, duration: 0.08, volume: 0.13, type: 'square' },
            {
                freq: 990,
                wordScale: 6,
                duration: 0.08,
                volume: 0.1,
                type: 'square',
                delay: 0.06,
                skipLite: true,
            },
        ],
        multiplierUp: [
            {
                freqByMultiplier: [440, 660, 880, 990, 1320],
                duration: 0.075,
                volume: 0.13,
                type: 'square',
            },
            {
                freqByMultiplier: [880, 1320, 1760, 1980, 2640],
                duration: 0.08,
                volume: 0.09,
                type: 'square',
                delay: 0.06,
                skipLite: true,
            },
        ],
        comboBreak: [
            { freq: 220, duration: 0.08, volume: 0.14, type: 'sawtooth' },
            { freq: 110, duration: 0.12, volume: 0.1, type: 'square', delay: 0.06 },
        ],
        timeout: [{ freq: 120, duration: 0.12, volume: 0.12, type: 'square' }],
        sessionComplete: [
            { freq: 660, duration: 0.08, volume: 0.11, type: 'square' },
            { freq: 990, duration: 0.08, volume: 0.1, type: 'square', delay: 0.08 },
            { freq: 1320, duration: 0.1, volume: 0.08, type: 'square', delay: 0.16 },
        ],
    },
    void: {
        correct: [{ freq: 620, duration: 0.06, volume: 0.08, type: 'sine', detune: -12 }],
        incorrect: [{ freq: 155, duration: 0.08, volume: 0.07, type: 'triangle' }],
        wordComplete: [{ freq: 440, duration: 0.08, volume: 0.07, type: 'sine' }],
        multiplierUp: [
            {
                freqByMultiplier: [330, 392, 440, 494, 587],
                duration: 0.08,
                volume: 0.07,
                type: 'sine',
            },
        ],
        comboBreak: [{ freq: 130, duration: 0.1, volume: 0.06, type: 'triangle' }],
        timeout: [{ freq: 110, duration: 0.1, volume: 0.06, type: 'triangle' }],
        sessionComplete: [{ freq: 523, duration: 0.12, volume: 0.07, type: 'sine' }],
    },
};

export const MUSIC_PRESETS = {
    arcadeLofi: { scheduler: 'style', volumeScale: 1 },
    starfieldAmbient: {
        scheduler: 'ambient',
        bpm: 48,
        root: 196,
        volumeScale: 0.58,
        type: 'sine',
        cutoff: 900,
        chords: [
            [-8, 0, 4],
            [-10, 2, 5],
            [-9, 1, 4],
            [-12, 0, 5],
        ],
        melody: [null, 7, null, null, 5, null, null, 4],
    },
    nebulaAmbient: {
        scheduler: 'ambient',
        bpm: 56,
        root: 174.61,
        volumeScale: 0.68,
        type: 'triangle',
        cutoff: 1250,
        chords: [
            [-8, 2, 5],
            [-10, 1, 4],
            [-9, 3, 6],
            [-12, 0, 5],
        ],
        melody: [5, null, 7, null, null, 4, null, 6],
    },
    gridPulse: {
        scheduler: 'pulse',
        bpm: 116,
        root: 110,
        volumeScale: 0.78,
        type: 'square',
        cutoff: 1800,
        pattern: [0, null, 4, 7, null, 4, 11, null, 7, null, 4, 0, null, 12, 11, 7],
    },
    gameCenterChiptune: {
        scheduler: 'chiptune',
        bpm: 132,
        root: 130.81,
        volumeScale: 0.92,
        type: 'square',
        cutoff: 2300,
        pattern: [0, 2, 4, 7, null, 7, 4, 2, 5, 7, 9, 12, null, 9, 7, 4],
    },
    shrineBells: {
        scheduler: 'bells',
        bpm: 62,
        root: 220,
        volumeScale: 0.55,
        type: 'sine',
        cutoff: 1450,
        pattern: [0, null, null, 2, null, 4, null, null, 7, null, 5, null, null, 4, null, null],
    },
    nightviewMinyo: {
        scheduler: 'minyo',
        bpm: 58,
        root: 220,
        volumeScale: 0.5,
        type: 'sine',
        cutoff: 1180,
        drone: [-12, 0],
        pattern: [0, null, 2, null, 4, null, 7, 5, null, 4, 2, null, 0, null, -3, null],
        reply: [null, null, 7, null, 5, null, 4, null, null, 2, null, 0],
    },
    matrixPulse: {
        scheduler: 'pulse',
        bpm: 94,
        root: 82.41,
        volumeScale: 0.58,
        type: 'square',
        cutoff: 1250,
        glitch: true,
        pattern: [0, null, 7, null, 0, 11, null, 7, null, 0, null, 4, 11, null, 7, null],
    },
    voidSilence: {
        scheduler: 'void',
        root: 110,
        volumeScale: 0.2,
        type: 'sine',
        cutoff: 360,
        duration: 5.2,
    },
};

export const AUDIO_WARN_THROTTLE_MS = 5000;

export const MUSIC_PROGRESSIONS = [
    [
        [220.0, 261.63, 329.63],
        [174.61, 220.0, 261.63],
        [196.0, 246.94, 293.66],
        [164.81, 207.65, 246.94],
    ],
    [
        [196.0, 246.94, 293.66],
        [146.83, 196.0, 246.94],
        [164.81, 207.65, 261.63],
        [174.61, 220.0, 261.63],
    ],
    [
        [164.81, 207.65, 246.94],
        [196.0, 246.94, 293.66],
        [146.83, 185.0, 220.0],
        [174.61, 220.0, 261.63],
    ],
    [
        [174.61, 220.0, 261.63],
        [164.81, 207.65, 246.94],
        [130.81, 164.81, 196.0],
        [146.83, 185.0, 220.0],
    ],
];

export const LOFI_MELODIES = [
    [null, 4, null, 2, null, null, 5, null, 4, null, null, 1, null, 2, null, null],
    [2, null, null, 4, null, 5, null, null, null, 4, null, 2, null, null, 1, null],
    [null, null, 5, null, 4, null, null, 2, null, 1, null, null, 2, null, null, 4],
    [4, null, 2, null, null, 1, null, null, 5, null, null, 4, null, 2, null, null],
];

export const RETRO_MELODIES = [
    [0, 2, 4, null, 7, 4, 2, null, 0, 2, 5, null, 4, 2, 0, null],
    [4, null, 2, 0, 2, null, 5, 4, 7, null, 5, 4, 2, null, 0, null],
];

export const NOTE_RATIOS = [1, 9 / 8, 5 / 4, 4 / 3, 3 / 2, 5 / 3, 15 / 8, 2];
