export const SETTINGS_VERSION = 2;

export const DEFAULT_SETTINGS = Object.freeze({
    settingsVersion: SETTINGS_VERSION,
    sfxEnabled: true,
    visualsEnabled: true,
    hudEnabled: true,
    shakeEnabled: true,
    floatEnabled: true,
    flashEnabled: true,
    failureFlashEnabled: true,
    crtEnabled: true,
    timerEnabled: true,
    timerSeconds: 15,
    timedXpBonusEnabled: true,
    timeoutFailureEnabled: false,
    fontChallengeEnabled: false,
    performanceProfile: 'balanced',
    musicEnabled: false,
    musicStyle: 'lofi',
    musicVolume: 0.16,
    backgroundTheme: 'default',
    pinnedBackgroundTheme: 'default',
    volume: 0.5,
    hudPosition: null,
    hudCollapsed: false,
});

export const BOOLEAN_SETTING_KEYS = Object.freeze([
    'sfxEnabled',
    'visualsEnabled',
    'hudEnabled',
    'shakeEnabled',
    'floatEnabled',
    'flashEnabled',
    'failureFlashEnabled',
    'crtEnabled',
    'timerEnabled',
    'timedXpBonusEnabled',
    'timeoutFailureEnabled',
    'fontChallengeEnabled',
    'musicEnabled',
    'hudCollapsed',
]);
