// Static configuration extracted from the preserved userscript behavior.
// Keep values stable unless a deliberate theme/audio behavior change is documented.

import { MUSIC_PRESETS, SOUND_PRESETS } from './audio-presets.js';
import { BACKGROUND_THEME_IDS } from './constants.js';

export {
    BACKGROUND_THEME_IDS as BACKGROUND_THEMES,
    MUSIC_STYLES,
    MUSIC_STYLE_LABELS,
    PERFORMANCE_PROFILES,
    PERFORMANCE_PROFILE_LABELS,
    REMOVED_BACKGROUND_THEME_FALLBACKS,
    THEME_ALIASES,
    TIMER_SECONDS_PRESETS,
} from './constants.js';

export const THEME_DEFINITIONS = {
    default: {
        id: 'default',
        label: 'Default',
        colors: {
            accent: '#ff9900',
            secondary: '#77ccff',
            success: '#77ff77',
            failure: '#ff5555',
            hudGlow: '#ff9900',
            flash: 'rgba(100,255,150,0.18)',
            failureFlash: 'rgba(255,70,90,0.18)',
            notification: '#ffe066',
            timerFast: '#ffe066',
            timerMedium: '#62d7ff',
            timerLow: '#ff9b42',
            timerCritical: '#ff5252',
            floatingText: '#ffe066',
            floatingShadow: '0 2px 6px rgba(0,0,0,0.8)',
            progress: 'linear-gradient(90deg, #00cc88, #00ffcc)',
            button: '#ff9900',
            buttonSoft: 'rgba(255,153,0,0.1)',
            banner: '#ffffff',
            bannerGlow: '#ff9900',
        },
        presets: {
            sound: 'arcade',
            floatingText: 'arcadeClassic',
            particles: 'arcadeBurst',
            combo: 'arcadePop',
            celebration: 'arcadePop',
            music: 'arcadeLofi',
        },
        intensity: { particles: 1, flash: 1, shake: 1, sound: 1, celebration: 1 },
        motion: { shakeScale: 1, effectIntensity: 1, allowIdle: true },
        background: { renderer: 'default', allowCanvasEffects: false, shootingStars: false },
    },
    starfield: {
        id: 'starfield',
        label: 'Starfield',
        colors: {
            accent: '#7dd3fc',
            secondary: '#e0f2fe',
            success: '#86efac',
            failure: '#fb7185',
            hudGlow: '#7dd3fc',
            flash: 'rgba(125,211,252,0.2)',
            failureFlash: 'rgba(251,113,133,0.14)',
            notification: '#dbeafe',
            timerFast: '#f8fafc',
            timerMedium: '#7dd3fc',
            timerLow: '#38bdf8',
            timerCritical: '#fb7185',
            floatingText: '#dbeafe',
            floatingShadow: '0 0 12px rgba(125,211,252,0.75)',
            progress: 'linear-gradient(90deg, #38bdf8, #e0f2fe)',
            button: '#7dd3fc',
            buttonSoft: 'rgba(125,211,252,0.12)',
            banner: '#f8fafc',
            bannerGlow: '#38bdf8',
        },
        presets: {
            sound: 'starfield',
            floatingText: 'softBlue',
            particles: 'starSparkles',
            combo: 'constellation',
            celebration: 'starfieldOrbit',
            music: 'starfieldAmbient',
        },
        intensity: { particles: 0.72, flash: 0.72, shake: 0.48, sound: 0.86, celebration: 0.72 },
        motion: { shakeScale: 0.35, effectIntensity: 0.78, allowIdle: true },
        background: { renderer: 'starfield', allowCanvasEffects: true, shootingStars: true },
    },
    nebula: {
        id: 'nebula',
        label: 'Nebula',
        colors: {
            accent: '#f0abfc',
            secondary: '#93c5fd',
            success: '#c4b5fd',
            failure: '#fb7185',
            hudGlow: '#d946ef',
            flash: 'rgba(216,180,254,0.2)',
            failureFlash: 'rgba(251,113,133,0.14)',
            notification: '#f5d0fe',
            timerFast: '#f0abfc',
            timerMedium: '#93c5fd',
            timerLow: '#f59e0b',
            timerCritical: '#fb7185',
            floatingText: '#f5d0fe',
            floatingShadow: '0 0 14px rgba(217,70,239,0.72)',
            progress: 'linear-gradient(90deg, #a78bfa, #f0abfc, #93c5fd)',
            button: '#d946ef',
            buttonSoft: 'rgba(217,70,239,0.12)',
            banner: '#f5d0fe',
            bannerGlow: '#a855f7',
        },
        presets: {
            sound: 'nebula',
            floatingText: 'cosmicGlow',
            particles: 'cosmicDust',
            combo: 'nebulaWave',
            celebration: 'nebulaBloom',
            music: 'nebulaAmbient',
        },
        intensity: { particles: 0.92, flash: 0.82, shake: 0.72, sound: 0.9, celebration: 0.95 },
        motion: { shakeScale: 0.55, effectIntensity: 0.95, allowIdle: true },
        background: { renderer: 'nebula', allowCanvasEffects: true, shootingStars: false },
    },
    grid: {
        id: 'grid',
        label: 'Grid',
        colors: {
            accent: '#00e5ff',
            secondary: '#38bdf8',
            success: '#22d3ee',
            failure: '#ff477e',
            hudGlow: '#00e5ff',
            flash: 'rgba(0,229,255,0.2)',
            failureFlash: 'rgba(255,71,126,0.16)',
            notification: '#67e8f9',
            timerFast: '#00e5ff',
            timerMedium: '#2563eb',
            timerLow: '#f97316',
            timerCritical: '#ff477e',
            floatingText: '#67e8f9',
            floatingShadow: '0 0 12px rgba(0,229,255,0.82)',
            progress: 'linear-gradient(90deg, #06b6d4, #2563eb)',
            button: '#00e5ff',
            buttonSoft: 'rgba(0,229,255,0.11)',
            banner: '#e0faff',
            bannerGlow: '#00e5ff',
        },
        presets: {
            sound: 'grid',
            floatingText: 'electricCyan',
            particles: 'pixelFragments',
            combo: 'scanPulse',
            celebration: 'gridScanBurst',
            music: 'gridPulse',
        },
        intensity: { particles: 1.08, flash: 0.96, shake: 1, sound: 1, celebration: 1.08 },
        motion: { shakeScale: 0.9, effectIntensity: 1.05, allowIdle: true },
        background: { renderer: 'grid', allowCanvasEffects: true, shootingStars: false },
    },
    gamecenter: {
        id: 'gamecenter',
        label: 'Game Center',
        colors: {
            accent: '#ff2bd6',
            secondary: '#00d9ff',
            success: '#fff05a',
            failure: '#ff4b4b',
            hudGlow: '#ff2bd6',
            flash: 'rgba(255,240,90,0.2)',
            failureFlash: 'rgba(255,75,75,0.16)',
            notification: '#fff05a',
            timerFast: '#fff05a',
            timerMedium: '#00d9ff',
            timerLow: '#ff8a00',
            timerCritical: '#ff4b4b',
            floatingText: '#fff05a',
            floatingShadow: '0 0 12px rgba(255,43,214,0.78)',
            progress: 'linear-gradient(90deg, #ff2bd6, #fff05a, #00d9ff)',
            button: '#ff2bd6',
            buttonSoft: 'rgba(255,43,214,0.12)',
            banner: '#fff05a',
            bannerGlow: '#ff2bd6',
        },
        presets: {
            sound: 'gamecenter',
            floatingText: 'pixelScore',
            particles: 'confettiPixels',
            combo: 'arcadeMarquee',
            celebration: 'gameCenterJackpot',
            music: 'gameCenterChiptune',
        },
        intensity: { particles: 1.18, flash: 1, shake: 1.05, sound: 1.04, celebration: 1.22 },
        motion: { shakeScale: 1.15, effectIntensity: 1.15, allowIdle: true },
        background: { renderer: 'gamecenter', allowCanvasEffects: true, shootingStars: false },
    },
    shrine: {
        id: 'shrine',
        label: 'Shrine',
        colors: {
            accent: '#f6d36b',
            secondary: '#fff7d6',
            success: '#facc6b',
            failure: '#dc6b5a',
            hudGlow: '#f6d36b',
            flash: 'rgba(246,211,107,0.18)',
            failureFlash: 'rgba(220,107,90,0.12)',
            notification: '#fff2b8',
            timerFast: '#fff2b8',
            timerMedium: '#f6d36b',
            timerLow: '#d97706',
            timerCritical: '#dc6b5a',
            floatingText: '#fff2b8',
            floatingShadow: '0 0 10px rgba(246,211,107,0.58)',
            progress: 'linear-gradient(90deg, #b7791f, #f6d36b, #fff7d6)',
            button: '#f6d36b',
            buttonSoft: 'rgba(246,211,107,0.1)',
            banner: '#fff7d6',
            bannerGlow: '#f6d36b',
        },
        presets: {
            sound: 'shrine',
            floatingText: 'goldLeaf',
            particles: 'sakuraPetals',
            combo: 'lanternGlow',
            celebration: 'shrineDrift',
            music: 'shrineBells',
        },
        intensity: { particles: 0.58, flash: 0.52, shake: 0.42, sound: 0.74, celebration: 0.56 },
        motion: { shakeScale: 0.35, effectIntensity: 0.68, allowIdle: true },
        background: { renderer: 'shrine', allowCanvasEffects: true, shootingStars: false },
    },
    nightview: {
        id: 'nightview',
        label: 'Night View',
        colors: {
            accent: '#f8d27a',
            secondary: '#9cc8ff',
            success: '#bfe8ff',
            failure: '#e46f75',
            hudGlow: '#9cc8ff',
            flash: 'rgba(156,200,255,0.18)',
            failureFlash: 'rgba(228,111,117,0.12)',
            notification: '#f8d27a',
            timerFast: '#f8f2c8',
            timerMedium: '#9cc8ff',
            timerLow: '#f0b35d',
            timerCritical: '#e46f75',
            floatingText: '#dcecff',
            floatingShadow: '0 0 13px rgba(156,200,255,0.72)',
            progress: 'linear-gradient(90deg, #274a7a, #9cc8ff, #f8d27a)',
            button: '#f8d27a',
            buttonSoft: 'rgba(248,210,122,0.11)',
            banner: '#f8f2c8',
            bannerGlow: '#8bbcff',
        },
        presets: {
            sound: 'nightview',
            floatingText: 'moonlitSilver',
            particles: 'fireflyWisps',
            combo: 'moonlitGate',
            celebration: 'nightviewGlow',
            music: 'nightviewMinyo',
        },
        intensity: { particles: 0.64, flash: 0.58, shake: 0.34, sound: 0.72, celebration: 0.62 },
        motion: { shakeScale: 0.28, effectIntensity: 0.7, allowIdle: true },
        background: { renderer: 'nightview', allowCanvasEffects: true, shootingStars: false },
    },
    matrix: {
        id: 'matrix',
        label: 'Matrix',
        colors: {
            accent: '#00ff88',
            secondary: '#00cc66',
            success: '#4ade80',
            failure: '#ef4444',
            hudGlow: '#00ff88',
            flash: 'rgba(0,255,136,0.2)',
            failureFlash: 'rgba(239,68,68,0.13)',
            notification: '#00ff88',
            timerFast: '#4ade80',
            timerMedium: '#22c55e',
            timerLow: '#a3e635',
            timerCritical: '#ef4444',
            floatingText: '#00ff88',
            floatingShadow: '0 0 12px rgba(0,255,136,0.82)',
            progress: 'linear-gradient(90deg, #007a3d, #00ff88)',
            button: '#00ff88',
            buttonSoft: 'rgba(0,255,136,0.1)',
            banner: '#bbf7d0',
            bannerGlow: '#00ff88',
        },
        presets: {
            sound: 'matrix',
            floatingText: 'terminalGreen',
            particles: 'matrixCode',
            combo: 'glitch',
            celebration: 'matrixGlitch',
            music: 'matrixPulse',
        },
        intensity: { particles: 0.86, flash: 0.74, shake: 0.74, sound: 0.92, celebration: 0.82 },
        motion: { shakeScale: 0.6, effectIntensity: 0.82, allowIdle: true },
        background: { renderer: 'matrix', allowCanvasEffects: true, shootingStars: false },
    },
    void: {
        id: 'void',
        label: 'Void',
        colors: {
            accent: '#e5e7eb',
            secondary: '#9ca3af',
            success: '#f9fafb',
            failure: '#9ca3af',
            hudGlow: '#e5e7eb',
            flash: 'rgba(229,231,235,0.08)',
            failureFlash: 'rgba(156,163,175,0.08)',
            notification: '#f9fafb',
            timerFast: '#f9fafb',
            timerMedium: '#d1d5db',
            timerLow: '#9ca3af',
            timerCritical: '#6b7280',
            floatingText: '#f9fafb',
            floatingShadow: '0 2px 8px rgba(0,0,0,0.5)',
            progress: 'linear-gradient(90deg, #6b7280, #f9fafb)',
            button: '#e5e7eb',
            buttonSoft: 'rgba(229,231,235,0.08)',
            banner: '#f9fafb',
            bannerGlow: '#9ca3af',
        },
        presets: {
            sound: 'void',
            floatingText: 'voidMinimal',
            particles: 'voidDust',
            combo: 'minimal',
            celebration: 'voidPulse',
            music: 'voidSilence',
        },
        intensity: { particles: 0.24, flash: 0.22, shake: 0.12, sound: 0.38, celebration: 0.25 },
        motion: { shakeScale: 0.1, effectIntensity: 0.22, allowIdle: false },
        background: { renderer: 'void', allowCanvasEffects: false, shootingStars: false },
    },
};

export const THEME_PRESENTATION_STYLES = {
    default: {
        panelBg: 'rgba(5,7,16,0.86)',
        panelBorder: 'rgba(255,153,0,0.34)',
        panelText: '#f8fafc',
        panelMuted: 'rgba(226,232,240,0.54)',
        panelDivider: 'rgba(255,255,255,0.13)',
        panelShadow: '0 0 0 1px rgba(255,153,0,0.08), 0 10px 28px rgba(0,0,0,0.36)',
        controlBg: 'rgba(255,153,0,0.08)',
        controlBorder: 'rgba(255,153,0,0.32)',
        fieldBg: 'rgba(2,5,14,0.72)',
        fieldBorder: 'rgba(119,204,255,0.62)',
        fieldGlow: 'rgba(0,220,255,0.18)',
        counterShadow: '0 0 8px rgba(255,224,102,0.58)',
        scanlineOpacity: '1',
        scanlineColor: 'rgba(0,0,0,0.18)',
        floatLabelBg: 'rgba(255,153,0,0.14)',
        floatLabelColor: '#fff6cc',
    },
    starfield: {
        panelBg: 'rgba(3,10,27,0.78)',
        panelBorder: 'rgba(125,211,252,0.36)',
        panelMuted: 'rgba(219,234,254,0.52)',
        panelShadow: '0 0 0 1px rgba(125,211,252,0.08), 0 0 24px rgba(56,189,248,0.14)',
        controlBg: 'rgba(125,211,252,0.09)',
        controlBorder: 'rgba(125,211,252,0.34)',
        fieldBg: 'rgba(1,7,23,0.74)',
        fieldBorder: 'rgba(224,242,254,0.54)',
        fieldGlow: 'rgba(125,211,252,0.22)',
        counterShadow: '0 0 10px rgba(125,211,252,0.62)',
        scanlineOpacity: '0.55',
        floatLabelBg: 'rgba(56,189,248,0.16)',
        floatLabelColor: '#f8fafc',
    },
    nebula: {
        panelBg: 'rgba(16,6,32,0.78)',
        panelBorder: 'rgba(240,171,252,0.36)',
        panelMuted: 'rgba(245,208,254,0.5)',
        panelShadow: '0 0 0 1px rgba(217,70,239,0.09), 0 0 30px rgba(147,51,234,0.16)',
        controlBg: 'rgba(217,70,239,0.1)',
        controlBorder: 'rgba(240,171,252,0.32)',
        fieldBg: 'rgba(10,5,24,0.72)',
        fieldBorder: 'rgba(147,197,253,0.5)',
        fieldGlow: 'rgba(217,70,239,0.24)',
        counterShadow: '0 0 11px rgba(240,171,252,0.58)',
        scanlineOpacity: '0.6',
        floatLabelBg: 'rgba(217,70,239,0.16)',
        floatLabelColor: '#f5d0fe',
    },
    grid: {
        panelBg: 'rgba(0,10,20,0.82)',
        panelBorder: 'rgba(0,229,255,0.44)',
        panelMuted: 'rgba(103,232,249,0.54)',
        panelShadow: '0 0 0 1px rgba(0,229,255,0.1), 0 0 26px rgba(0,229,255,0.18)',
        controlBg: 'rgba(0,229,255,0.09)',
        controlBorder: 'rgba(0,229,255,0.38)',
        fieldBg: 'rgba(0,8,18,0.78)',
        fieldBorder: 'rgba(0,229,255,0.62)',
        fieldGlow: 'rgba(0,229,255,0.24)',
        counterShadow: '0 0 9px rgba(0,229,255,0.65)',
        scanlineOpacity: '0.78',
        floatLabelBg: 'rgba(0,229,255,0.14)',
        floatLabelColor: '#e0faff',
    },
    gamecenter: {
        panelBg: 'rgba(13,7,28,0.8)',
        panelBorder: 'rgba(255,43,214,0.42)',
        panelMuted: 'rgba(255,240,90,0.5)',
        panelShadow: '0 0 0 1px rgba(255,43,214,0.09), 0 0 30px rgba(255,43,214,0.16)',
        controlBg: 'rgba(255,43,214,0.1)',
        controlBorder: 'rgba(255,43,214,0.36)',
        fieldBg: 'rgba(12,5,22,0.76)',
        fieldBorder: 'rgba(0,217,255,0.58)',
        fieldGlow: 'rgba(255,43,214,0.24)',
        counterShadow: '0 0 10px rgba(255,240,90,0.68)',
        scanlineOpacity: '0.82',
        floatLabelBg: 'rgba(255,43,214,0.18)',
        floatLabelColor: '#fff05a',
    },
    shrine: {
        panelBg: 'rgba(28,16,8,0.66)',
        panelBorder: 'rgba(246,211,107,0.4)',
        panelMuted: 'rgba(255,247,214,0.54)',
        panelShadow: '0 0 0 1px rgba(246,211,107,0.08), 0 12px 32px rgba(35,18,4,0.32)',
        controlBg: 'rgba(246,211,107,0.09)',
        controlBorder: 'rgba(246,211,107,0.34)',
        fieldBg: 'rgba(20,12,7,0.62)',
        fieldBorder: 'rgba(255,247,214,0.5)',
        fieldGlow: 'rgba(246,211,107,0.2)',
        counterShadow: '0 0 9px rgba(246,211,107,0.58)',
        scanlineOpacity: '0.34',
        scanlineColor: 'rgba(41,20,4,0.16)',
        floatLabelBg: 'rgba(246,211,107,0.14)',
        floatLabelColor: '#fff7d6',
    },
    nightview: {
        panelBg: 'rgba(3,9,20,0.74)',
        panelBorder: 'rgba(156,200,255,0.34)',
        panelMuted: 'rgba(220,235,255,0.52)',
        panelShadow: '0 0 0 1px rgba(156,200,255,0.08), 0 12px 32px rgba(2,7,18,0.38)',
        controlBg: 'rgba(248,210,122,0.08)',
        controlBorder: 'rgba(156,200,255,0.28)',
        fieldBg: 'rgba(3,8,18,0.72)',
        fieldBorder: 'rgba(156,200,255,0.48)',
        fieldGlow: 'rgba(129,181,255,0.2)',
        counterShadow: '0 0 10px rgba(248,210,122,0.48)',
        scanlineOpacity: '0.38',
        scanlineColor: 'rgba(3,12,30,0.2)',
        floatLabelBg: 'rgba(156,200,255,0.13)',
        floatLabelColor: '#f8f2c8',
    },
    matrix: {
        panelBg: 'rgba(0,9,5,0.84)',
        panelBorder: 'rgba(0,255,136,0.38)',
        panelMuted: 'rgba(0,255,136,0.48)',
        panelShadow: '0 0 0 1px rgba(0,255,136,0.08), 0 0 24px rgba(0,255,136,0.12)',
        controlBg: 'rgba(0,255,136,0.08)',
        controlBorder: 'rgba(0,255,136,0.34)',
        fieldBg: 'rgba(0,6,3,0.78)',
        fieldBorder: 'rgba(0,255,136,0.54)',
        fieldGlow: 'rgba(0,255,136,0.18)',
        counterShadow: '0 0 9px rgba(0,255,136,0.62)',
        scanlineOpacity: '0.68',
        scanlineColor: 'rgba(0,20,10,0.22)',
        floatLabelBg: 'rgba(0,255,136,0.12)',
        floatLabelColor: '#bbf7d0',
    },
    void: {
        panelBg: 'rgba(4,5,7,0.72)',
        panelBorder: 'rgba(229,231,235,0.18)',
        panelMuted: 'rgba(209,213,219,0.42)',
        panelDivider: 'rgba(229,231,235,0.08)',
        panelShadow: '0 8px 22px rgba(0,0,0,0.28)',
        controlBg: 'rgba(229,231,235,0.04)',
        controlBorder: 'rgba(229,231,235,0.16)',
        fieldBg: 'rgba(3,4,6,0.68)',
        fieldBorder: 'rgba(156,163,175,0.22)',
        fieldGlow: 'rgba(229,231,235,0.06)',
        counterShadow: '0 0 6px rgba(229,231,235,0.28)',
        scanlineOpacity: '0.18',
        scanlineColor: 'rgba(229,231,235,0.08)',
        floatLabelBg: 'rgba(229,231,235,0.08)',
        floatLabelColor: '#e5e7eb',
    },
};

export const CANVAS_BACKGROUND_THEMES = Object.freeze(
    BACKGROUND_THEME_IDS.filter((theme) => THEME_DEFINITIONS[theme].background.allowCanvasEffects),
);

export const SHOOTING_STAR_THEMES = Object.freeze(
    BACKGROUND_THEME_IDS.filter((theme) => THEME_DEFINITIONS[theme].background.shootingStars),
);

export const THEME_MUSIC_MODE_LABELS = {
    arcadeLofi: 'STYLE',
    starfieldAmbient: 'AMBIENT',
    nebulaAmbient: 'AMBIENT',
    gridPulse: 'PULSE',
    gameCenterChiptune: 'CHIPTUNE',
    shrineBells: 'BELLS',
    nightviewMinyo: 'MINYO',
    matrixPulse: 'PULSE',
    voidSilence: 'FOCUS',
};

export const BACKGROUND_THEME_LABELS = Object.freeze(
    Object.fromEntries(
        BACKGROUND_THEME_IDS.map((theme) => [theme, THEME_DEFINITIONS[theme].label.toUpperCase()]),
    ),
);

export const SHRINE_IMAGE_URL =
    'https://raw.githubusercontent.com/Mikhail2577/marumori-userscripts/' +
    'f997afc94074989ec324590d7df08960a2633f52/' +
    'even-more-gamified/assets/shrine-garden.jpg';

export const NIGHTVIEW_IMAGE_URL =
    'https://raw.githubusercontent.com/Mikhail2577/marumori-userscripts/' +
    'f997afc94074989ec324590d7df08960a2633f52/' +
    'even-more-gamified/assets/nightview.png';

export const FLOATING_TEXT_PRESETS = {
    arcadeClassic: {
        base: { color: 'var(--mm-theme-floating-text)', shadow: 'var(--mm-theme-floating-shadow)' },
        events: {
            incorrect: { color: 'var(--mm-theme-failure)', label: 'MISS' },
            wordComplete: { color: 'var(--mm-theme-success)', fontSize: '16px', label: 'CLEAR' },
            milestone: { color: 'var(--mm-theme-banner)', fontSize: '20px', label: 'BONUS' },
            rewind: { color: 'var(--mm-theme-secondary)' },
        },
    },
    softBlue: {
        base: {
            color: '#dbeafe',
            shadow: '0 0 12px rgba(125,211,252,0.78)',
            motion: 'drift',
        },
        events: {
            correct: { label: 'ORBIT' },
            incorrect: {
                color: '#fb7185',
                shadow: '0 0 9px rgba(251,113,133,0.48)',
                label: 'DRIFT',
            },
            wordComplete: { color: '#f8fafc', fontSize: '16px', label: 'CHARTED' },
            multiplierUp: { label: 'ALIGN' },
            milestone: { color: '#f8fafc', fontSize: '20px', label: 'STELLAR' },
        },
    },
    cosmicGlow: {
        base: {
            color: '#f5d0fe',
            shadow: '0 0 14px rgba(217,70,239,0.75)',
            motion: 'wave',
        },
        events: {
            correct: { label: 'AURA' },
            incorrect: { color: '#fb7185', label: 'RIFT' },
            wordComplete: { color: '#c4b5fd', fontSize: '16px', label: 'BLOOM' },
            multiplierUp: { label: 'NOVA' },
            milestone: { color: '#f0abfc', fontSize: '20px', label: 'ASCEND' },
        },
    },
    electricCyan: {
        base: {
            color: '#67e8f9',
            shadow: '0 0 12px rgba(0,229,255,0.82)',
            motion: 'snap',
        },
        events: {
            correct: { label: 'SYNC' },
            incorrect: { color: '#ff477e', label: 'FAULT' },
            wordComplete: { color: '#22d3ee', fontSize: '16px', label: 'ROUTE' },
            multiplierUp: { label: 'BOOST' },
            milestone: { color: '#e0faff', fontSize: '20px', label: 'OVERCLOCK' },
        },
    },
    pixelScore: {
        base: {
            color: '#fff05a',
            shadow: '0 0 13px rgba(255,43,214,0.75)',
            motion: 'snap',
        },
        events: {
            correct: { label: 'BONUS' },
            incorrect: { color: '#ff4b4b', label: 'MISS' },
            wordComplete: { color: '#00d9ff', fontSize: '16px', label: 'STAGE' },
            multiplierUp: { label: 'JACKPOT' },
            milestone: { color: '#fff05a', fontSize: '20px', label: 'HI-SCORE' },
        },
    },
    goldLeaf: {
        base: {
            color: '#fff2b8',
            shadow: '0 0 10px rgba(246,211,107,0.58)',
            motion: 'drift',
        },
        events: {
            correct: { label: '清明' },
            incorrect: { color: '#dc6b5a', label: '乱' },
            wordComplete: { color: '#f6d36b', fontSize: '16px', label: '満開' },
            multiplierUp: { label: '灯' },
            milestone: { color: '#fff7d6', fontSize: '19px', label: '成就' },
        },
    },
    moonlitSilver: {
        base: {
            color: '#fff2c6',
            shadow: '0 0 11px rgba(248,210,122,0.58)',
            motion: 'drift',
        },
        events: {
            correct: { label: '灯' },
            incorrect: { color: '#e46f75', label: '影' },
            wordComplete: { color: '#bfe8ff', fontSize: '16px', label: '月明' },
            multiplierUp: { color: '#f8d27a', label: '祭囃子' },
            milestone: { color: '#f8f2c8', fontSize: '19px', label: '宵祭' },
        },
    },
    terminalGreen: {
        base: {
            color: '#00ff88',
            shadow: '0 0 12px rgba(0,255,136,0.82)',
            fontFamily: 'Consolas, Monaco, monospace',
            motion: 'glitch',
        },
        events: {
            correct: { label: 'ACCESS' },
            incorrect: {
                color: '#ef4444',
                shadow: '0 0 10px rgba(239,68,68,0.58)',
                label: 'TRACE',
            },
            wordComplete: { color: '#bbf7d0', fontSize: '16px', label: 'DECRYPT' },
            multiplierUp: { label: 'ROOT' },
            milestone: { color: '#bbf7d0', fontSize: '20px', label: 'BREACH' },
        },
    },
    voidMinimal: {
        base: {
            color: '#f9fafb',
            shadow: '0 2px 8px rgba(0,0,0,0.5)',
            fontSize: '12px',
            motion: 'minimal',
        },
        events: {
            correct: { label: 'OK' },
            incorrect: { color: '#9ca3af', label: 'NO' },
            wordComplete: { color: '#e5e7eb', fontSize: '13px', label: 'DONE' },
            multiplierUp: { label: '+' },
            milestone: { color: '#f9fafb', fontSize: '16px', label: 'PEAK' },
        },
    },
};

export const PARTICLE_PRESETS = {
    arcadeBurst: {
        shape: 'dot',
        motion: 'burst',
        color: 'var(--mm-theme-notification)',
        count: 8,
        liteCount: 2,
        lifetimeMs: 700,
        spread: 72,
        size: 5,
        events: {
            incorrect: { color: 'var(--mm-theme-failure)', count: 5, liteCount: 1 },
            wordComplete: { color: 'var(--mm-theme-success)', count: 10, liteCount: 2 },
            milestone: { count: 14, liteCount: 3, spread: 110, size: 6 },
            timeout: { color: 'var(--mm-theme-failure)', count: 4, liteCount: 1 },
        },
    },
    starSparkles: {
        shape: 'star',
        motion: 'drift',
        color: '#dbeafe',
        count: 7,
        liteCount: 1,
        lifetimeMs: 950,
        spread: 85,
        size: 6,
        events: {
            milestone: { count: 12, spread: 120 },
            incorrect: { color: '#fb7185', count: 3 },
        },
    },
    cosmicDust: {
        shape: 'ring',
        motion: 'drift',
        color: '#f0abfc',
        count: 9,
        liteCount: 1,
        lifetimeMs: 1050,
        spread: 96,
        size: 7,
        events: {
            wordComplete: { color: '#c4b5fd', count: 11 },
            incorrect: { color: '#fb7185', count: 4 },
        },
    },
    pixelFragments: {
        shape: 'pixel',
        motion: 'burst',
        color: '#00e5ff',
        count: 9,
        liteCount: 2,
        lifetimeMs: 760,
        spread: 86,
        size: 5,
        events: {
            incorrect: { color: '#ff477e', count: 6 },
            timeout: { color: '#ff477e', count: 4 },
        },
    },
    confettiPixels: {
        shape: 'pixel',
        motion: 'burst',
        color: '#fff05a',
        count: 12,
        liteCount: 2,
        lifetimeMs: 850,
        spread: 100,
        size: 5,
        events: {
            correct: { count: 9 },
            multiplierUp: { color: '#ff2bd6', count: 12 },
            milestone: { count: 16, spread: 128 },
            incorrect: { color: '#ff4b4b', count: 5 },
        },
    },
    sakuraPetals: {
        shape: 'petal',
        motion: 'fall',
        color: '#f6d36b',
        count: 6,
        liteCount: 1,
        lifetimeMs: 1150,
        spread: 78,
        size: 7,
        events: {
            incorrect: { color: '#dc6b5a', count: 2, lifetimeMs: 850 },
            milestone: { count: 10, spread: 105 },
        },
    },
    fireflyWisps: {
        shape: 'dot',
        motion: 'drift',
        color: '#f8d27a',
        count: 4,
        liteCount: 1,
        lifetimeMs: 1350,
        spread: 64,
        size: 4,
        events: {
            correct: { count: 3, lifetimeMs: 1250 },
            wordComplete: { color: '#f8f2c8', count: 6, spread: 74, lifetimeMs: 1500 },
            multiplierUp: { color: '#f8d27a', count: 5, spread: 70 },
            milestone: { color: '#f8f2c8', count: 8, spread: 92, size: 5 },
            incorrect: { color: '#e46f75', count: 2, lifetimeMs: 900 },
            timeout: { color: '#e46f75', count: 2, lifetimeMs: 860 },
            comboBreak: { color: '#e46f75', count: 2 },
        },
    },
    matrixCode: {
        shape: 'glyph',
        motion: 'glitch',
        color: '#00ff88',
        glyphs: '01日月火水木金土',
        count: 7,
        liteCount: 1,
        lifetimeMs: 760,
        spread: 76,
        size: 12,
        events: {
            incorrect: { color: '#ef4444', glyphs: '01', count: 4 },
            comboBreak: { color: '#ef4444', glyphs: '0101', count: 5 },
        },
    },
    voidDust: {
        shape: 'dot',
        motion: 'drift',
        color: '#e5e7eb',
        count: 2,
        liteCount: 0,
        lifetimeMs: 650,
        spread: 32,
        size: 3,
        events: {
            milestone: { count: 4, liteCount: 1 },
            incorrect: { color: '#9ca3af', count: 1 },
        },
    },
};

export const COMBO_EFFECT_PRESETS = {
    arcadePop: {
        style: 'pop',
        color: 'var(--mm-theme-banner)',
        shadow: '0 0 20px var(--mm-theme-banner-glow), 0 0 40px var(--mm-theme-banner-glow)',
        celebrations: ['🎉', '✨', '⚡', '🔥', '💫', '🎊', '🌟', '💥', '⭐', '💎', '🏆'],
    },
    constellation: {
        style: 'float',
        color: '#f8fafc',
        shadow: '0 0 22px rgba(125,211,252,0.95), 0 0 46px rgba(56,189,248,0.55)',
        celebrations: ['✦', '✧', '⋆', '★'],
    },
    nebulaWave: {
        style: 'wave',
        color: '#f5d0fe',
        shadow: '0 0 22px rgba(217,70,239,0.9), 0 0 46px rgba(147,197,253,0.55)',
        celebrations: ['✦', '✧', '◇', '◆'],
    },
    scanPulse: {
        style: 'scan',
        color: '#e0faff',
        shadow: '0 0 20px rgba(0,229,255,0.95), 0 0 42px rgba(37,99,235,0.65)',
        celebrations: ['▣', '◆', '◇', '✦'],
    },
    arcadeMarquee: {
        style: 'marquee',
        color: '#fff05a',
        shadow: '0 0 20px rgba(255,43,214,0.95), 0 0 42px rgba(0,217,255,0.65)',
        celebrations: ['🎉', '✨', '⚡', '🎊', '🌟', '💥', '⭐', '🏆'],
    },
    lanternGlow: {
        style: 'calm',
        color: '#fff7d6',
        shadow: '0 0 18px rgba(246,211,107,0.75), 0 0 34px rgba(183,121,31,0.35)',
        celebrations: ['✦', '◇', '◆', '花'],
    },
    moonlitGate: {
        style: 'calm',
        color: '#f8f2c8',
        shadow: '0 0 16px rgba(248,210,122,0.64), 0 0 32px rgba(156,200,255,0.28)',
        celebrations: ['月', '灯', '祭', '花'],
    },
    glitch: {
        style: 'glitch',
        color: '#bbf7d0',
        shadow: '0 0 18px rgba(0,255,136,0.9), 0 0 36px rgba(0,204,102,0.55)',
        celebrations: ['0', '1', '日', '月'],
    },
    minimal: {
        style: 'minimal',
        color: '#f9fafb',
        shadow: '0 0 12px rgba(229,231,235,0.38)',
        celebrations: ['•', '·', '✦'],
    },
};

export const CELEBRATION_CHOREOGRAPHY_PRESETS = {
    arcadePop: {
        effects: ['pop', 'rise', 'burst', 'spin'],
        count: 1,
        liteCount: 1,
        spread: 72,
        size: 52,
        durationMs: 850,
        answerAccent: 'pop',
    },
    starfieldOrbit: {
        effects: ['orbit', 'drift', 'rise'],
        count: 2,
        liteCount: 1,
        spread: 92,
        size: 44,
        durationMs: 1100,
        answerAccent: 'orbit',
    },
    nebulaBloom: {
        effects: ['bloom', 'drift', 'pulse'],
        count: 2,
        liteCount: 1,
        spread: 98,
        size: 48,
        durationMs: 1120,
        answerAccent: 'bloom',
    },
    gridScanBurst: {
        effects: ['scan', 'burst', 'glitch'],
        count: 2,
        liteCount: 1,
        spread: 86,
        size: 46,
        durationMs: 760,
        answerAccent: 'scan',
    },
    gameCenterJackpot: {
        effects: ['pop', 'burst', 'spin'],
        count: 3,
        liteCount: 1,
        spread: 112,
        size: 54,
        durationMs: 820,
        answerAccent: 'jackpot',
    },
    shrineDrift: {
        effects: ['calm', 'drift', 'rise'],
        count: 1,
        liteCount: 1,
        spread: 58,
        size: 43,
        durationMs: 1280,
        answerAccent: 'shimmer',
    },
    nightviewGlow: {
        effects: ['calm', 'drift', 'rise'],
        count: 1,
        liteCount: 1,
        spread: 54,
        size: 40,
        durationMs: 1320,
        answerAccent: 'shimmer',
    },
    matrixGlitch: {
        effects: ['glitch', 'scan', 'burst'],
        count: 2,
        liteCount: 1,
        spread: 74,
        size: 45,
        durationMs: 720,
        answerAccent: 'glitch',
    },
    voidPulse: {
        effects: ['pulse', 'calm'],
        count: 1,
        liteCount: 0,
        spread: 28,
        size: 34,
        durationMs: 620,
        answerAccent: 'pulse',
    },
};

export const CSS_THEME_VARIABLES = {
    accent: '--mm-theme-accent',
    secondary: '--mm-theme-secondary',
    success: '--mm-theme-success',
    failure: '--mm-theme-failure',
    hudGlow: '--mm-theme-hud-glow',
    flash: '--mm-theme-flash',
    failureFlash: '--mm-theme-failure-flash',
    notification: '--mm-theme-notification',
    timerFast: '--mm-theme-timer-fast',
    timerMedium: '--mm-theme-timer-medium',
    timerLow: '--mm-theme-timer-low',
    timerCritical: '--mm-theme-timer-critical',
    floatingText: '--mm-theme-floating-text',
    floatingShadow: '--mm-theme-floating-shadow',
    progress: '--mm-theme-progress',
    button: '--mm-theme-button',
    buttonSoft: '--mm-theme-button-soft',
    banner: '--mm-theme-banner',
    bannerGlow: '--mm-theme-banner-glow',
};

export const CSS_THEME_PRESENTATION_VARIABLES = {
    panelBg: '--mm-theme-panel-bg',
    panelBorder: '--mm-theme-panel-border',
    panelText: '--mm-theme-panel-text',
    panelMuted: '--mm-theme-panel-muted',
    panelDivider: '--mm-theme-panel-divider',
    panelShadow: '--mm-theme-panel-shadow',
    controlBg: '--mm-theme-control-bg',
    controlBorder: '--mm-theme-control-border',
    fieldBg: '--mm-theme-field-bg',
    fieldBorder: '--mm-theme-field-border',
    fieldGlow: '--mm-theme-field-glow',
    counterShadow: '--mm-theme-counter-shadow',
    scanlineOpacity: '--mm-theme-scanline-opacity',
    scanlineColor: '--mm-theme-scanline-color',
    floatLabelBg: '--mm-theme-float-label-bg',
    floatLabelColor: '--mm-theme-float-label-color',
};

export const TEMP_EFFECT_SELECTOR =
    '.mm-float, .mm-celebrate, .mm-theme-particle, .mm-answer-accent';

export const THEME_PRESET_REGISTRY = {
    sound: SOUND_PRESETS,
    floatingText: FLOATING_TEXT_PRESETS,
    particles: PARTICLE_PRESETS,
    combo: COMBO_EFFECT_PRESETS,
    celebration: CELEBRATION_CHOREOGRAPHY_PRESETS,
    music: MUSIC_PRESETS,
};
